// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCec5k5C2x2f2mg_5z5wgt4qiwkCXp8-kU',
    appId: '1:1008364863114:web:abdd336d956a5cd2b97773',
    messagingSenderId: '1008364863114',
    projectId: 'fluttertodoapp-724da',
    authDomain: 'fluttertodoapp-724da.firebaseapp.com',
    storageBucket: 'fluttertodoapp-724da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ8Zv9HKlQF05TR9YTpZeYsDC3OLLzWaE',
    appId: '1:1008364863114:android:7c5ff0fd8677b3a5b97773',
    messagingSenderId: '1008364863114',
    projectId: 'fluttertodoapp-724da',
    storageBucket: 'fluttertodoapp-724da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBDQc_vvmmsDqyokmo2QcymDhjERDtB2g',
    appId: '1:1008364863114:ios:c15c9075ad1ff5c9b97773',
    messagingSenderId: '1008364863114',
    projectId: 'fluttertodoapp-724da',
    storageBucket: 'fluttertodoapp-724da.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBDQc_vvmmsDqyokmo2QcymDhjERDtB2g',
    appId: '1:1008364863114:ios:c15c9075ad1ff5c9b97773',
    messagingSenderId: '1008364863114',
    projectId: 'fluttertodoapp-724da',
    storageBucket: 'fluttertodoapp-724da.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCec5k5C2x2f2mg_5z5wgt4qiwkCXp8-kU',
    appId: '1:1008364863114:web:3abd675271deefeeb97773',
    messagingSenderId: '1008364863114',
    projectId: 'fluttertodoapp-724da',
    authDomain: 'fluttertodoapp-724da.firebaseapp.com',
    storageBucket: 'fluttertodoapp-724da.appspot.com',
  );
}
